import Foundation
import CloudKit

// MARK: - Overhead Expense
//
// Indirect company cost not tied to a specific project — rent, office payroll,
// software subscriptions, insurance premiums, etc. Tracked as a flat top-level
// ledger (not nested under a project) so the same record can be allocated
// across multiple projects at report time.
//
// Allocation is a *read-time* computation (see `DataStore.allocateOverhead`):
// each expense carries a `distributionMode` plus an optional list of target
// project IDs, and the allocation helper computes pro-rata shares from
// `Project.contractAmount`. Nothing is written back to individual projects.
struct OverheadExpense: Identifiable, Hashable {
    let recordID: CKRecord.ID
    var id: CKRecord.ID { recordID }

    var date: Date
    var amount: Decimal
    var category: OverheadCategory
    var vendor: String
    var expenseDescription: String
    var notes: String

    /// Recurrence on the template entry. Child instances (generated by
    /// `DataStore.generateRecurringOverhead`) carry `.none` here and link back
    /// via `parentRecurringID`.
    var recurrence: RecurrenceInterval

    /// Set on generated instances — points to the `recordID.recordName` of the
    /// template that spawned them. Lets us skip children when iterating
    /// recurrence roots and lets the UI group them.
    var parentRecurringID: String?

    var distributionMode: OverheadDistributionMode

    /// When `distributionMode == .specificProjects`, the `recordName`s of
    /// projects that should absorb this expense.
    var distributionProjectIDs: [String]

    var attachments: [Attachment]

    init(
        recordID: CKRecord.ID = CKRecord.ID(recordName: UUID().uuidString),
        date: Date = Date(),
        amount: Decimal = 0,
        category: OverheadCategory = .other,
        vendor: String = "",
        expenseDescription: String = "",
        notes: String = "",
        recurrence: RecurrenceInterval = .none,
        parentRecurringID: String? = nil,
        distributionMode: OverheadDistributionMode = .allActive,
        distributionProjectIDs: [String] = [],
        attachments: [Attachment] = []
    ) {
        self.recordID = recordID
        self.date = date
        self.amount = amount
        self.category = category
        self.vendor = vendor
        self.expenseDescription = expenseDescription
        self.notes = notes
        self.recurrence = recurrence
        self.parentRecurringID = parentRecurringID
        self.distributionMode = distributionMode
        self.distributionProjectIDs = distributionProjectIDs
        self.attachments = attachments
    }

    /// True when this entry is the template for a recurring series.
    /// Children (generated instances) always return false.
    var isRecurringTemplate: Bool {
        recurrence != .none && parentRecurringID == nil
    }
}

// MARK: - Category

enum OverheadCategory: String, CaseIterable, Codable, Hashable {
    case rent = "Rent"
    case utilities = "Utilities"
    case officePayroll = "Office Payroll"
    case insurance = "Insurance"
    case software = "Software & Subscriptions"
    case supplies = "Office Supplies"
    case vehicle = "Vehicle & Fleet"
    case professionalFees = "Professional Fees"
    case marketing = "Marketing"
    case generalMaterials = "General Materials"
    case other = "Other"

    var icon: String {
        switch self {
        case .rent: return "building.2.fill"
        case .utilities: return "bolt.fill"
        case .officePayroll: return "person.badge.clock.fill"
        case .insurance: return "shield.lefthalf.filled"
        case .software: return "app.badge.fill"
        case .supplies: return "printer.fill"
        case .vehicle: return "car.fill"
        case .professionalFees: return "scalemass.fill"
        case .marketing: return "megaphone.fill"
        case .generalMaterials: return "shippingbox.fill"
        case .other: return "ellipsis.circle.fill"
        }
    }
}

// MARK: - Recurrence

enum RecurrenceInterval: String, CaseIterable, Codable, Hashable {
    case none = "One-time"
    case weekly = "Weekly"
    case monthly = "Monthly"
    case quarterly = "Quarterly"
    case yearly = "Yearly"

    /// Advance `date` by one interval. Returns nil for `.none`.
    func next(after date: Date, calendar: Calendar = .current) -> Date? {
        switch self {
        case .none: return nil
        case .weekly: return calendar.date(byAdding: .weekOfYear, value: 1, to: date)
        case .monthly: return calendar.date(byAdding: .month, value: 1, to: date)
        case .quarterly: return calendar.date(byAdding: .month, value: 3, to: date)
        case .yearly: return calendar.date(byAdding: .year, value: 1, to: date)
        }
    }
}

// MARK: - Distribution

enum OverheadDistributionMode: String, CaseIterable, Codable, Hashable {
    /// Distributed pro-rata (by `contractAmount`) across every project that
    /// was active on the expense's `date`.
    case allActive = "All Active Projects"

    /// Distributed pro-rata across a hand-picked subset of projects.
    case specificProjects = "Specific Projects"

    /// Never distributed to projects — appears only in company-level totals.
    case companyOnly = "Company Only"

    /// Amortized to a daily rate over the expense's coverage period (one
    /// interval of the source recurrence — e.g. Weekly $2000 → $285.71/day for
    /// 7 days; one-time = a single day). For each day, the day's portion is
    /// split across projects with at least one Gantt task scheduled that day
    /// whose `Assigned to` is filled in — weighted by the number of distinct
    /// assignees on each project that day. Computed read-time so retroactive
    /// Gantt edits flow through automatically.
    case scheduleDaily = "Schedule (Daily)"

    var shortLabel: String {
        switch self {
        case .allActive: return "All Active"
        case .specificProjects: return "Custom"
        case .companyOnly: return "Company"
        case .scheduleDaily: return "Schedule"
        }
    }
}
